# Generated by Django 2.0.13 on 2019-07-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190722_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='blog/static/media/', verbose_name='Ссылка картинки'),
        ),
    ]
