# Generated by Django 2.0.13 on 2019-07-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190722_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='index',
            field=models.IntegerField(default=int, verbose_name='Индекс'),
            preserve_default=False,
        ),
    ]
