# Generated by Django 2.0.13 on 2019-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190724_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boturl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
